(() => {
      const ingresoInput = document.getElementById('inputIngresoMensual');
        const btnGuardarIngreso = document.getElementById('btnGuardarIngreso');
          const formMovimiento = document.getElementById('formMovimiento');
            const tablaMovimientosBody = document.querySelector('#tablaMovimientos tbody');
              const movimientosTotales = document.getElementById('movimientosTotales');
                const saldoSemanalDiv = document.getElementById('saldoSemanal');
                  const saldoMensualDiv = document.getElementById('saldoMensual');
                    const resumenMensualBody = document.querySelector('#resumenMensual tbody');
                      const btnResetear = document.getElementById('btnResetear');

                        const CATEGORIAS = ['Necesidad', 'Deseo', 'Ahorro'];
                          const PORCENTAJES = { Necesidad: 50, Deseo: 30, Ahorro: 20 };

                            const formatMonto = val => val.toLocaleString('es-AR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

                              function obtenerSemanaDelMes(fecha) {
                                  const dia = fecha.getDate();
                                      return Math.ceil(dia / 7);
                                        }

                                          function guardarDatos() {
                                              localStorage.setItem('ingresoMensual', ingresoMensual.toString());
                                                  localStorage.setItem('movimientos', JSON.stringify(movimientos));
                                                    }
                                                      function cargarDatos() {
                                                          const ingresoGuardado = localStorage.getItem('ingresoMensual');
                                                              ingresoMensual = ingresoGuardado ? parseFloat(ingresoGuardado) : 100000;

                                                                  const movGuardados = localStorage.getItem('movimientos');
                                                                      movimientos = movGuardados ? JSON.parse(movGuardados) : [];
                                                                        }

                                                                          let ingresoMensual = 100000;
                                                                            let movimientos = [];

                                                                              function actualizarIngresoInput() {
                                                                                  ingresoInput.value = ingresoMensual.toFixed(2);
                                                                                    }

                                                                                      function agregarMovimiento({ fecha, categoria, subcategoria, monto }) {
                                                                                          const fechaObj = new Date(fecha + 'T00:00:00');
                                                                                              if (isNaN(fechaObj)) return false;
                                                                                                  if (!CATEGORIAS.includes(categoria)) return false;
                                                                                                      if (!subcategoria.trim()) return false;
                                                                                                          if (monto <= 0) return false;

                                                                                                              const semanaMes = obtenerSemanaDelMes(fechaObj);

                                                                                                                  movimientos.push({ fecha, categoria, subcategoria, monto, semanaMes });
                                                                                                                      movimientos.sort((a,b) => new Date(a.fecha) - new Date(b.fecha));
                                                                                                                          guardarDatos();
                                                                                                                              return true;
                                                                                                                                }

                                                                                                                                  function limpiarForm() {
                                                                                                                                      formMovimiento.reset();
                                                                                                                                          const inputFecha = document.getElementById('inputFecha');
                                                                                                                                              inputFecha.valueAsDate = new Date();
                                                                                                                                                }

                                                                                                                                                  function renderMovimientos() {
                                                                                                                                                      tablaMovimientosBody.innerHTML = '';
                                                                                                                                                          if(movimientos.length === 0) {
                                                                                                                                                                tablaMovimientosBody.innerHTML = `<tr><td colspan="5" style="text-align:center; color:#777;">No hay movimientos registrados</td></tr>`;
                                                                                                                                                                      movimientosTotales.textContent = '';
                                                                                                                                                                            return;
                                                                                                                                                                                }
                                                                                                                                                                                    movimientos.forEach(mov => {
                                                                                                                                                                                          const tr = document.createElement('tr');
                                                                                                                                                                                                tr.innerHTML = `
                                                                                                                                                                                                        <td data-label="Fecha">${mov.fecha}</td>
                                                                                                                                                                                                                <td data-label="Semana">${mov.semanaMes}</td>
                                                                                                                                                                                                                        <td data-label="Categoría">${mov.categoria}</td>
                                                                                                                                                                                                                                <td data-label="Subcategoría">${mov.subcategoria}</td>
                                                                                                                                                                                                                                        <td data-label="Monto">$${formatMonto(mov.monto)}</td>
                                                                                                                                                                                                                                              `;
                                                                                                                                                                                                                                                    tablaMovimientosBody.appendChild(tr);
                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                            movimientosTotales.textContent = `Total movimientos: ${movimientos.length}`;
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                function calcularPresupuestoSemanal() {
                                                                                                                                                                                                                                                                    const semanas = 4.33;
                                                                                                                                                                                                                                                                        const semanal = ingresoMensual / semanas;

                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                  Necesidad: semanal * (PORCENTAJES.Necesidad / 100),
                                                                                                                                                                                                                                                                                        Deseo: semanal * (PORCENTAJES.Deseo / 100),
                                                                                                                                                                                                                                                                                              Ahorro: semanal * (PORCENTAJES.Ahorro / 100),
                                                                                                                                                                                                                                                                                                    totalSemanal: semanal
                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                            function calcularPresupuestoMensual() {
                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                      Necesidad: ingresoMensual * (PORCENTAJES.Necesidad / 100),
                                                                                                                                                                                                                                                                                                                            Deseo: ingresoMensual * (PORCENTAJES.Deseo / 100),
                                                                                                                                                                                                                                                                                                                                  Ahorro: ingresoMensual * (PORCENTAJES.Ahorro / 100),
                                                                                                                                                                                                                                                                                                                                        totalMensual: ingresoMensual
                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                function calcularGastos() {
                                                                                                                                                                                                                                                                                                                                                    const hoy = new Date();
                                                                                                                                                                                                                                                                                                                                                        const semanaActual = obtenerSemanaDelMes(hoy);

                                                                                                                                                                                                                                                                                                                                                            const gastosSemana = { Necesidad:0, Deseo:0, Ahorro:0 };
                                                                                                                                                                                                                                                                                                                                                                const gastosMes = { Necesidad:0, Deseo:0, Ahorro:0 };

                                                                                                                                                                                                                                                                                                                                                                    movimientos.forEach(mov => {
                                                                                                                                                                                                                                                                                                                                                                          if(CATEGORIAS.includes(mov.categoria)) {
                                                                                                                                                                                                                                                                                                                                                                                  gastosMes[mov.categoria] += mov.monto;
                                                                                                                                                                                                                                                                                                                                                                                          if(mov.semanaMes === semanaActual) {
                                                                                                                                                                                                                                                                                                                                                                                                    gastosSemana[mov.categoria] += mov.monto;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                          return { gastosSemana, gastosMes, semanaActual };
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                              function mostrarSaldos() {
                                                                                                                                                                                                                                                                                                                                                                                                                                  const { gastosSemana, gastosMes, semanaActual } = calcularGastos();
                                                                                                                                                                                                                                                                                                                                                                                                                                      const presupuestoSemanal = calcularPresupuestoSemanal();
                                                                                                                                                                                                                                                                                                                                                                                                                                          const presupuestoMensual = calcularPresupuestoMensual();

                                                                                                                                                                                                                                                                                                                                                                                                                                              saldoSemanalDiv.innerHTML = `<strong>Semana ${semanaActual} (Presupuesto semanal: $${formatMonto(presupuestoSemanal.totalSemanal)})</strong>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  saldoSemanalDiv.appendChild(document.createElement('br'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                      CATEGORIAS.forEach(cat => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const saldo = presupuestoSemanal[cat] - gastosSemana[cat];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const span = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        span.className = 'status ' + (saldo >= 0 ? 'positivo' : 'negativo');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              span.textContent = `${cat}: $${formatMonto(saldo)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saldoSemanalDiv.appendChild(span);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          saldoSemanalDiv.appendChild(document.createTextNode(' '));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  saldoMensualDiv.innerHTML = `<strong>Mes actual (Presupuesto mensual: $${formatMonto(presupuestoMensual.totalMensual)})</strong><br>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      CATEGORIAS.forEach(cat => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const saldo = presupuestoMensual[cat] - gastosMes[cat];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const span = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        span.className = 'status ' + (saldo >= 0 ? 'positivo' : 'negativo');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              span.textContent = `${cat}: $${formatMonto(saldo)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saldoMensualDiv.appendChild(span);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          saldoMensualDiv.appendChild(document.createTextNode(' '));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function mostrarResumen() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resumenMensualBody.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { gastosMes } = calcularGastos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const presupuestoMensual = calcularPresupuestoMensual();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CATEGORIAS.forEach(cat => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const total = gastosMes[cat];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const porcentaje = presupuestoMensual[cat] > 0 ? (total / presupuestoMensual[cat]) * 100 : 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const tr = document.createElement('tr');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tr.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>${cat}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>$${formatMonto(total)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>${porcentaje.toFixed(1)}%</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              resumenMensualBody.appendChild(tr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function resetearDatos() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(confirm('¿Está seguro que quiere resetear y comenzar un nuevo mes? Se borrarán todos los movimientos registrados.')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                movimientos = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      guardarDatos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            renderMovimientos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  mostrarSaldos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarResumen();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function inicializar() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cargarDatos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        actualizarIngresoInput();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const inputFecha = document.getElementById('inputFecha');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                inputFecha.valueAsDate = new Date();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    btnGuardarIngreso.addEventListener('click', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const val = parseFloat(ingresoInput.value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (isNaN(val) || val < 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert('Ingrese un valor válido para el ingreso mensual');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ingresoInput.focus();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ingresoMensual = val;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                guardarDatos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      actualizarIngresoInput();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarSaldos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  mostrarResumen();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('Ingreso mensual actualizado');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                formMovimiento.addEventListener('submit', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const fecha = document.getElementById('inputFecha').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const categoria = document.getElementById('selectCategoria').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const subcategoria = document.getElementById('inputSubcategoria').value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const monto = parseFloat(document.getElementById('inputMonto').value);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!fecha || !categoria || !subcategoria || isNaN(monto) || monto <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert('Por favor complete todos los campos correctamente.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const agregado = agregarMovimiento({ fecha, categoria, subcategoria, monto });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!agregado) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert('Datos inválidos. Revise los campos.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderMovimientos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarSaldos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              mostrarResumen();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    limpiarForm();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btnResetear.addEventListener('click', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resetearDatos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                renderMovimientos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mostrarSaldos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarResumen();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.addEventListener('DOMContentLoaded', inicializar);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })();